# -*- coding: utf-8 -*-
"""Proj_MohammadAminKiani_4043644008_SAM3 (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dC7H1wSQgFwEA9gRv2jVmYKZOH2fpAA8

# Mohammad Amin Kiani 4043644008
# DIP - Proj : SAM 3 Open-Vocabulary Video Tracking
# ui.ac.ir 404-405

This notebook tracks a moving object in a video using a text prompt, then exports:
- overlay MP4
- GIF
- 2D centroid trajectory plot
- CSV of centroid coordinates
"""

!nvidia-smi

"""## 1- https://huggingface.co/facebook/sam3

### Important notes

The official SAM 3 repository currently requires Python 3.12+, PyTorch 2.7+, and CUDA 12.6+.
If Colab runtime does not satisfy these requirements, we should use a local GPU environment or a Colab runtime that matches them.
**Access to the checkpoint on Hugging Face is required.**
"""

!pip install -q --upgrade pip

!pip install -q \
torch torchvision torchaudio \
einops \
decord \
pycocotools \
hydra-core \
omegaconf \
iopath \
timm \
opencv-python \
matplotlib \
pandas \
imageio \
ffmpeg-python

!pip install -q triton

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/facebookresearch/sam3.git
# %cd sam3
!pip install -e .
!pip install -e ".[notebooks]"
# %cd ..

"""### Authentication

Log in to Hugging Face with an access token that has permission to download the SAM 3 checkpoints.
One common approach is to run `hf auth login` in the notebook or set `HF_TOKEN` as an environment variable.

"""

# Commented out IPython magic to ensure Python compatibility.
!mkdir checkpoints
# %cd checkpoints

!wget https://dl.fbaipublicfiles.com/sam3/sam3_hiera_large.pt

# %cd ..

!pip install -q huggingface_hub

from huggingface_hub import notebook_login
notebook_login() # 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

import inspect
print(inspect.signature(build_sam3_video_predictor))

predictor = build_sam3_video_predictor()
print(dir(predictor))

from huggingface_hub import snapshot_download

snapshot_download(
    repo_id="facebook/sam3",
    local_dir="sam3_weights"
)

import os

for root, dirs, files in os.walk("sam3_weights"):
    for f in files:
        print(os.path.join(root, f))

from sam3.model_builder import build_sam3_video_predictor

predictor = build_sam3_video_predictor()

print("loaded")

import torch
import triton
import einops
import decord
import sam3

print("Torch:", torch.__version__)
print("Triton:", triton.__version__)
print("SAM3 imported successfully")

from sam3.model_builder import build_sam3_video_predictor

import sam3
print(sam3.__file__)

import sam3.model_builder
print(dir(sam3.model_builder))

import sam3.model_builder as mb
dir(mb)

from sam3.model_builder import build_sam3_video_predictor
import inspect

print(inspect.signature(build_sam3_video_predictor))

predictor = build_sam3_video_predictor()

print(type(predictor))
print(dir(predictor))

predictor = build_sam3_video_predictor(
    checkpoint="checkpoints/sam3_hiera_large.pt"
)

print("Predictor loaded.")

predictor = build_sam3_video_predictor(
    async_loading_frames=True
)

"""### Run Main Proj

دانلود ویدیوی ورودی از یوتیوب
"""

!yt-dlp -f "best[ext=mp4]" --download-sections "*00:00:15-00:00:20" "https://www.youtube.com/watch?v=CSvFpBOe8eY" -o "input_video.mp4" --force-overwrites

"""استخراج فریم‌ها"""

import cv2
import os

video_path = "input_video.mp4"

cap = cv2.VideoCapture(video_path)

os.makedirs("frames", exist_ok=True)

i = 0

while True:
    ret, frame = cap.read()

    if not ret:
        break

    cv2.imwrite(f"frames/{i:05d}.jpg", frame)
    i += 1

cap.release()

print("Frames:", i)

"""بارگذاری مدل‌ها:"""

from sam3.model_builder import build_sam3_video_predictor

predictor = build_sam3_video_predictor(
    checkpoint="checkpoints/sam3_hiera_large.pt"
)

import torch

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

print(DEVICE)

response = predictor.handle_request(
    request={
        "type": "start_session",
        "resource_path": video_path
    }
)

session_id = response["session_id"]

print(session_id)

"""پرامپت:"""

TEXT_PROMPT = "guitar"

response = predictor.handle_request(
    request={
        "type": "add_prompt",
        "session_id": session_id,
        "frame_index": 0,
        "text": TEXT_PROMPT
    }
)

"""گرفتن خروجی:"""

outputs = response["outputs"]

print(outputs.keys())

results = predictor.handle_request(
    request={
        "type": "propagate_in_video",
        "session_id": session_id
    }
)

"""استخراج ماسک و مرکز:"""

import numpy as np
import pandas as pd

centroids = []

for frame_idx, output in enumerate(results["outputs"]):

    mask = output["masks"][0]

    mask = mask.astype(np.uint8)

    M = cv2.moments(mask)

    if M["m00"] > 0:

        cX = int(M["m10"]/M["m00"])
        cY = int(M["m01"]/M["m00"])

        centroids.append(
            [frame_idx, cX, cY]
        )

"""ذخیره اکسل:"""

df = pd.DataFrame(
    centroids,
    columns=[
        "frame",
        "x",
        "y"
    ]
)

df.to_csv(
    "trajectory.csv",
    index=False
)

"""رسم مسیر:"""

import matplotlib.pyplot as plt

plt.figure(figsize=(8,8))

plt.plot(
    df["x"],
    df["y"],
    "-o",
    markersize=2
)

plt.gca().invert_yaxis()

plt.xlabel("X")
plt.ylabel("Y")

plt.title("Trajectory")

plt.grid()

plt.savefig(
    "trajectory.png"
)

plt.show()

"""ساخت ویدئوی خروجی:"""

cap = cv2.VideoCapture(video_path)

w = int(cap.get(3))
h = int(cap.get(4))
fps = int(cap.get(5))

fourcc = cv2.VideoWriter_fourcc(*"mp4v")

out = cv2.VideoWriter(
    "output.mp4",
    fourcc,
    fps,
    (w, h)
)

trajectory = []

frame_idx = 0

while True:

    ret, frame = cap.read()

    if not ret:
        break

    row = df[
        df.frame == frame_idx
    ]

    if len(row):

        x = int(row.x.values[0])
        y = int(row.y.values[0])

        trajectory.append(
            (x, y)
        )

        cv2.circle(
            frame,
            (x, y),
            8,
            (0,255,0),
            -1
        )

        for i in range(
            1,
            len(trajectory)
        ):

            cv2.line(
                frame,
                trajectory[i-1],
                trajectory[i],
                (0,0,255),
                2
            )

    out.write(frame)

    frame_idx += 1

cap.release()
out.release()

"""### Download generated artifacts

After execution, download the MP4, GIF, PNG, and CSV from the output folder.

"""

!ffmpeg \
-i output.mp4 \
-r 10 \
output.gif

"""## 2- https://modelscope.cn/models/facebook/sam3

### Installation:
"""

# =====================================================
# STEP 1 : Clean Environment
# =====================================================

!pip uninstall -y \
opencv-python \
opencv-python-headless \
opencv-contrib-python \
numpy \
transformers \
accelerate \
timm \
sam3

# -----------------------------------------------------

!pip install -U pip setuptools wheel

# -----------------------------------------------------

!pip install \
numpy==1.26.4 \
scipy \
pandas \
matplotlib \
pillow \
imageio \
imageio-ffmpeg \
tqdm \
einops \
ninja \
ftfy==6.1.1 \
iopath \
portalocker

# -----------------------------------------------------

!pip install \
torch \
torchvision \
torchaudio

# -----------------------------------------------------

!pip install \
opencv-python-headless==4.10.0.84

# -----------------------------------------------------

!pip install \
git+https://github.com/facebookresearch/sam3.git

# -----------------------------------------------------

!pip install \
modelscope

# -----------------------------------------------------

!pip install \
ffmpeg-python

"""### Downloading SAM3 checkpoint from ModelScope:"""

# -----------------------------------------------------

import os
import cv2
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print("="*60)
print("Torch :", torch.__version__)
print("CUDA  :", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU   :", torch.cuda.get_device_name(0))

print("Numpy :", np.__version__)
print("="*60)

from modelscope import snapshot_download
import os

MODEL_DIR = "/content/checkpoints"

os.makedirs(MODEL_DIR, exist_ok=True)

print("Downloading SAM3 checkpoint from ModelScope...")

model_path = snapshot_download(
    "facebook/sam3",
    local_dir=MODEL_DIR
)

print("="*60)
print("Download finished.")
print("Model Path:")
print(model_path)
print("="*60)

for root, dirs, files in os.walk(MODEL_DIR):
    for f in files:
        print(os.path.join(root, f))

import inspect
from sam3.model_builder import build_sam3_video_predictor

print("=" * 80)
print(inspect.signature(build_sam3_video_predictor))
print("=" * 80)
print(inspect.getsource(build_sam3_video_predictor))

import inspect

from sam3.model.sam3_video_predictor import Sam3VideoPredictor

print("=" * 80)
print(inspect.signature(Sam3VideoPredictor.__init__))
print("=" * 80)
print(inspect.getsource(Sam3VideoPredictor.__init__))

import torch
from sam3.model_builder import build_sam3_video_predictor

checkpoint = "/content/checkpoints/sam3.pt"

predictor = build_sam3_video_predictor(
    checkpoint_path=checkpoint
)

print("="*60)
print("Predictor loaded successfully.")
print(type(predictor))
print("="*60)

import traceback

try:
    predictor = build_sam3_video_predictor(
        checkpoint_path="/content/checkpoints/sam3.pt"
    )

    print("SUCCESS")
    print(type(predictor))

except Exception:
    traceback.print_exc()

"""### My Video:

#### Local video:
"""

from google.colab import files
import os

uploaded = files.upload()

video_path = list(uploaded.keys())[0]

print("="*60)
print("Video Loaded Successfully")
print(video_path)
print("="*60)

assert os.path.exists(video_path)

import cv2

cap = cv2.VideoCapture(video_path)

frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
fps = cap.get(cv2.CAP_PROP_FPS)
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

cap.release()

print("="*60)
print(f"Frames : {frame_count}")
print(f"FPS    : {fps}")
print(f"Size   : {width} x {height}")
print("="*60)

"""برش 5 ثانیه از ویدیوی کامل"""

!ffmpeg -y \
-i full_video.mp4 \
-ss 00:00:52 \
-t 5 \
-c:v libx264 \
-preset fast \
-crf 18 \
-c:a copy \
input_video.mp4

"""#### OR video from YouTube:

Toxicity
"""

!yt-dlp -f "best[ext=mp4]" --download-sections "*00:02:01-00:02:06" "https://youtu.be/Ug4Yv2hY5no?si=Igc6envN3fQlBFEx" -o "input_video.mp4" --force-overwrites

"""Gate 21"""

!yt-dlp -f "best[ext=mp4]" --download-sections "*00:02:59-00:03:07" "https://youtu.be/IWMJH1MBIZE?si=KZonfNO79VNAbJXY" -o "input_video.mp4" --force-overwrites

"""### Process Input_Video:"""

import cv2

cap = cv2.VideoCapture("input_video.mp4")

frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
fps = cap.get(cv2.CAP_PROP_FPS)

print("Frames :", frames)
print("FPS :", fps)
print("Duration :", frames / fps)

cap.release()

import gc
import torch

try:
    predictor.handle_request(
        request={
            "type":"close_session",
            "session_id":session_id
        }
    )
except:
    pass

del predictor

gc.collect()

torch.cuda.empty_cache()

torch.cuda.ipc_collect()

print(torch.cuda.memory_summary())

video_path2 = "/content/input_video.mp4"

response = predictor.handle_request(
    request={
        "type": "start_session",
        "resource_path": video_path2,
        "offload_video_to_cpu":True
    }
)

session_id=response["session_id"]

print(session_id)

response=predictor.handle_request(
    request={
        "type":"add_prompt",
        "session_id":session_id,
        "frame_index":0,
        "text":"lead singer"
    }
)

outputs=response["outputs"]

print(outputs.keys())

print(hasattr(predictor, "handle_stream_request"))
print(hasattr(predictor, "propagate_in_video"))

outputs_per_frame = {}

for response in predictor.handle_stream_request(
    request=dict(
        type="propagate_in_video",
        session_id=session_id,
    )
):
    frame_idx = response["frame_index"]
    outputs_per_frame[frame_idx] = response["outputs"]

print("Frames tracked:", len(outputs_per_frame))

outputs_per_frame = {}

for response in predictor.propagate_in_video(
    session_id,
    "forward"
):
    outputs_per_frame[response["frame_index"]] = response["outputs"]

print(len(outputs_per_frame))

import numpy as np

print("Number of tracked frames:", len(outputs_per_frame))

first_frame = min(outputs_per_frame.keys())

print("First frame:", first_frame)

out = outputs_per_frame[first_frame]

print("="*60)

for k, v in out.items():
    print(k)

    if hasattr(v, "shape"):
        print("shape =", v.shape)

    elif isinstance(v, list):
        print("list length =", len(v))

    elif isinstance(v, dict):
        print("dict keys =", v.keys())

    else:
        print(type(v))

"""### Run Main 1:

مرحله ۱ : استخراج Centroid
"""

import cv2
import numpy as np
import pandas as pd

centroids = []

for frame_idx in sorted(outputs_per_frame.keys()):

    out = outputs_per_frame[frame_idx]

    mask = out["out_binary_masks"][0]

    mask = (mask > 0).astype(np.uint8)

    contours, _ = cv2.findContours(
        mask,
        cv2.RETR_EXTERNAL,
        cv2.CHAIN_APPROX_SIMPLE
    )

    if len(contours) == 0:

        centroids.append([frame_idx, np.nan, np.nan])

        continue

    cnt = max(contours, key=cv2.contourArea)

    M = cv2.moments(cnt)

    if M["m00"] == 0:

        centroids.append([frame_idx, np.nan, np.nan])

        continue

    cx = M["m10"] / M["m00"]
    cy = M["m01"] / M["m00"]

    centroids.append([frame_idx, cx, cy])

centroids = pd.DataFrame(
    centroids,
    columns=["frame","x","y"]
)

centroids.head()

"""مرحله ۲ : ذخیره CSV"""

centroids.to_csv(
    "trajectory.csv",
    index=False
)

print(centroids.head())

"""مرحله ۳ : رسم مسیر حرکت"""

import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))

plt.plot(
    centroids["x"],
    centroids["y"],
    "-o",
    markersize=3
)

plt.gca().invert_yaxis()

plt.xlabel("X")

plt.ylabel("Y")

plt.title("Centroid Trajectory")

plt.grid(True)

plt.savefig(
    "trajectory.png",
    dpi=300
)

plt.show()

"""مرحله ۴ : ساخت ویدئوی خروجی"""

import cv2
import numpy as np

cap = cv2.VideoCapture("input_video.mp4")

fps = cap.get(cv2.CAP_PROP_FPS)

w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))

h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

writer = cv2.VideoWriter(
    "output.mp4",
    cv2.VideoWriter_fourcc(*"mp4v"),
    fps,
    (w,h)
)

trajectory = []

frame_id = 0

while True:

    ret, frame = cap.read()

    if not ret:
        break

    if frame_id in outputs_per_frame:

        out = outputs_per_frame[frame_id]

        mask = out["out_binary_masks"][0]

        mask = (mask>0).astype(np.uint8)

        color = np.zeros_like(frame)

        color[:,:,1] = mask*255

        frame = cv2.addWeighted(
            frame,
            1,
            color,
            0.45,
            0
        )

        row = centroids.iloc[frame_id]

        if not np.isnan(row.x):

            p = (int(row.x), int(row.y))

            trajectory.append(p)

            cv2.circle(
                frame,
                p,
                5,
                (0,0,255),
                -1
            )

            for i in range(1,len(trajectory)):

                cv2.line(
                    frame,
                    trajectory[i-1],
                    trajectory[i],
                    (255,0,0),
                    2
                )

    writer.write(frame)

    frame_id += 1

writer.release()

cap.release()

print("output.mp4 created")

"""مرحله ۵ : ساخت GIF"""

import imageio.v2 as imageio

reader = imageio.get_reader("output.mp4")

frames = []

for frame in reader:

    frames.append(frame)

imageio.mimsave(
    "output.gif",
    frames,
    fps=10
)

print("output.gif created")

"""### Run Main 2:

مرحله اول — استخراج حرفه‌ای مرکز
"""

import cv2
import numpy as np
import pandas as pd

records = []

MIN_AREA = 150

for frame_idx in sorted(outputs_per_frame.keys()):

    out = outputs_per_frame[frame_idx]

    mask = out["out_binary_masks"][0].astype(np.uint8)

    box = out["out_boxes_xywh"][0]

    # ---------- Morphology ----------

    kernel = np.ones((5,5), np.uint8)

    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernel)

    mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel)

    # ---------- Largest Connected Component ----------

    num_labels, labels, stats, centroids = cv2.connectedComponentsWithStats(mask)

    if num_labels <= 1:

        x, y, w, h = box

        cx = x + w/2

        cy = y + h/2

        area = 0

    else:

        largest = 1 + np.argmax(stats[1:, cv2.CC_STAT_AREA])

        area = stats[largest, cv2.CC_STAT_AREA]

        if area < MIN_AREA:

            x, y, w, h = box

            cx = x + w/2

            cy = y + h/2

        else:

            component = (labels == largest).astype(np.uint8)

            M = cv2.moments(component)

            if M["m00"] > 0:

                cx = M["m10"]/M["m00"]

                cy = M["m01"]/M["m00"]

            else:

                x, y, w, h = box

                cx = x + w/2

                cy = y + h/2

    records.append([

        frame_idx,

        float(cx),

        float(cy),

        float(area)

    ])

trajectory = pd.DataFrame(

    records,

    columns=["frame","x","y","area"]

)

trajectory.to_csv(

    "trajectory.csv",

    index=False

)

trajectory.head()

"""مرحله دوم — حذف پرش‌های مسیر"""

trajectory["x_smooth"] = trajectory["x"].rolling(
    7,
    center=True,
    min_periods=1
).median()

trajectory["y_smooth"] = trajectory["y"].rolling(
    7,
    center=True,
    min_periods=1
).median()

"""مرحله سوم — رسم حرفه‌ای Trajectory"""

import matplotlib.pyplot as plt

plt.figure(figsize=(8,8))

plt.plot(
    trajectory["x_smooth"],
    trajectory["y_smooth"],
    color="royalblue",
    linewidth=2
)

plt.scatter(
    trajectory["x_smooth"],
    trajectory["y_smooth"],
    s=10
)

plt.scatter(
    trajectory.iloc[0]["x_smooth"],
    trajectory.iloc[0]["y_smooth"],
    c="green",
    s=120,
    label="Start"
)

plt.scatter(
    trajectory.iloc[-1]["x_smooth"],
    trajectory.iloc[-1]["y_smooth"],
    c="red",
    s=120,
    label="End"
)

plt.gca().invert_yaxis()

plt.grid(True)

plt.legend()

plt.xlabel("X")

plt.ylabel("Y")

plt.title("Centroid Trajectory")

plt.savefig(
    "trajectory.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

"""مرحله چهارم — ویدئوی حرفه‌ای"""

import cv2
import numpy as np

cap = cv2.VideoCapture("input_video.mp4")

fps = cap.get(cv2.CAP_PROP_FPS)
w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

writer = cv2.VideoWriter(
    "output.mp4",
    cv2.VideoWriter_fourcc(*"mp4v"),
    fps,
    (w, h)
)

trajectory_points = []

while True:

    ret, frame = cap.read()

    if not ret:
        break

    frame_id = int(cap.get(cv2.CAP_PROP_POS_FRAMES)) - 1

    if frame_id in outputs_per_frame:

        out = outputs_per_frame[frame_id]

        # ---------------- Mask ----------------

        mask = out["out_binary_masks"][0].astype(np.uint8)

        # ---------------- Bounding Box ----------------

        box = out["out_boxes_xywh"][0]

        x, y, bw, bh = box.astype(int)

        # ---------------- Overlay Mask ----------------

        overlay = frame.copy()

        overlay[mask > 0] = (0, 255, 0)

        frame = cv2.addWeighted(
            frame,
            0.75,
            overlay,
            0.25,
            0
        )

        # ---------------- Mask Edge ----------------

        edges = cv2.Canny(mask * 255, 50, 150)

        frame[edges > 0] = (0, 255, 255)

        # ---------------- Bounding Box ----------------

        cv2.rectangle(
            frame,
            (x, y),
            (x + bw, y + bh),
            (255, 255, 0),
            2
        )

        # ---------------- Smoothed Centroid ----------------

        row = trajectory.iloc[frame_id]

        cx = int(row["x_smooth"])
        cy = int(row["y_smooth"])

        trajectory_points.append((cx, cy))

        # ---------------- Current Position ----------------

        cv2.circle(
            frame,
            (cx, cy),
            6,
            (0, 0, 255),
            -1
        )

        # ---------------- Trajectory ----------------

        if len(trajectory_points) > 1:

            cv2.polylines(
                frame,
                [np.array(trajectory_points, np.int32)],
                False,
                (255, 0, 0),
                3
            )

        # ---------------- Confidence ----------------

        if "out_probs" in out:

            score = float(out["out_probs"][0])

            cv2.putText(
                frame,
                f"Score: {score:.2f}",
                (15, 30),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.7,
                (255, 255, 255),
                2
            )

        # ---------------- Frame Number ----------------

        cv2.putText(
            frame,
            f"Frame: {frame_id}",
            (15, 60),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.7,
            (255, 255, 255),
            2
        )

    writer.write(frame)

writer.release()
cap.release()

print("=" * 60)
print("output.mp4 created successfully")
print("=" * 60)

"""مرحله پنجم — آمار پروژه"""

valid = trajectory["area"] > 0

success = int(valid.sum())

total = len(trajectory)

success_rate = 100 * success / total

distance = np.sqrt(

    np.diff(trajectory["x_smooth"])**2 +

    np.diff(trajectory["y_smooth"])**2

).sum()

print("="*50)

print(f"Tracked Frames : {success}/{total}")

print(f"Success Rate   : {success_rate:.2f}%")

print(f"Trajectory Len : {distance:.2f} pixels")

print("="*50)