# -*- coding: utf-8 -*-
"""HW1_MohammadAminKiani_4043644008_2D_signals_and_transforms.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N9__GW4D3osHlN0b5iw7CL4SnrHgd_qv

# Mohammad Amin Kiani 4043644008
# DIP - HW1 : 2D_signals_and_transforms
# ui.ac.ir 404-405

«به‌جای متلب از پایتون استفاده شده است، که همانند متلب یک محیط مناسب برای محاسبات عددی و رسم نمودار است.»
"""

!pip install numpy matplotlib scipy

"""بررسی رابطه بین شکل فضایی و رفتار فرکانسی

**تبدیل فوریه نشان می‌دهد که اطلاعات لبه‌ها در فرکانس‌های بالا قرار دارند**
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.fft import fft2, fftshift, fftfreq

# =========================================================
# 1) ساخت شبکه دوبعدی
# =========================================================
N = 512          # تعداد نمونه‌ها در هر بعد
L = 10.0         # دامنه مکانی: از -L تا +L

x = np.linspace(-L, L, N, endpoint=False)
y = np.linspace(-L, L, N, endpoint=False)
X, Y = np.meshgrid(x, y)

dx = x[1] - x[0]
dy = y[1] - y[0]

# محور فرکانس
u = fftshift(fftfreq(N, d=dx))
v = fftshift(fftfreq(N, d=dy))
U, V = np.meshgrid(u, v)

# =========================================================
# 2) تعریف توابع دوبعدی
# =========================================================
def rectangle_2d(X, Y, a=2.0, b=1.5):
    """
    Rectangle with width 2a and height 2b
    """
    return ((np.abs(X) <= a) & (np.abs(Y) <= b)).astype(float)

def pyramid_2d(X, Y, a=3.0, b=3.0):
    """
    2D pyramid = product of two 1D triangular functions
    """
    tx = np.maximum(1.0 - np.abs(X) / a, 0.0)
    ty = np.maximum(1.0 - np.abs(Y) / b, 0.0)
    return tx * ty

def gaussian_2d(X, Y, sigma=1.2):
    """
    Normalized 2D Gaussian
    """
    return (1.0 / (2.0 * np.pi * sigma**2)) * np.exp(-(X**2 + Y**2) / (2.0 * sigma**2))

def peak_2d(X, Y, eps=1e-3):
    """
    Peak function: 1/r, regularized at origin
    """
    R = np.sqrt(X**2 + Y**2)
    return 1.0 / np.maximum(R, eps)

def exponential_decay_2d(X, Y, a=1.2):
    """
    Radial exponential decay: exp(-a r)
    """
    R = np.sqrt(X**2 + Y**2)
    return np.exp(-a * R)

# =========================================================
# 3) محاسبه FFT دوبعدی
# =========================================================
def compute_fft2(signal):
    """
    Continuous FT approximation:
    FFT * dx * dy
    """
    return fftshift(fft2(signal)) * dx * dy

# =========================================================
# 4) رسم نتیجه
# =========================================================
def show_spatial_and_frequency(signal, title, cmap="gray"):
    F = compute_fft2(signal)
    magnitude = np.abs(F)
    log_magnitude = np.log1p(magnitude)   # نمایش بهتر

    fig, axes = plt.subplots(1, 2, figsize=(12, 5))

    im0 = axes[0].imshow(
        signal,
        extent=[x.min(), x.max(), y.min(), y.max()],
        origin="lower",
        cmap=cmap,
        aspect="auto"
    )
    axes[0].set_title(f"{title} - Spatial Domain")
    axes[0].set_xlabel("x")
    axes[0].set_ylabel("y")
    plt.colorbar(im0, ax=axes[0], fraction=0.046, pad=0.04)

    im1 = axes[1].imshow(
        log_magnitude,
        extent=[u.min(), u.max(), v.min(), v.max()],
        origin="lower",
        cmap=cmap,
        aspect="auto"
    )
    axes[1].set_title(f"{title} - Frequency Domain (log magnitude)")
    axes[1].set_xlabel("u")
    axes[1].set_ylabel("v")
    plt.colorbar(im1, ax=axes[1], fraction=0.046, pad=0.04)

    plt.tight_layout()
    plt.show()

# =========================================================
# 5) تولید و نمایش همه توابع
# =========================================================
rect = rectangle_2d(X, Y, a=2.0, b=1.5)
pyr = pyramid_2d(X, Y, a=3.0, b=3.0)
gauss = gaussian_2d(X, Y, sigma=1.2)
peak = peak_2d(X, Y, eps=1e-3)
decay = exponential_decay_2d(X, Y, a=1.2)

show_spatial_and_frequency(rect, "Rectangle")
show_spatial_and_frequency(pyr, "Pyramid")
show_spatial_and_frequency(gauss, "Gaussian")
show_spatial_and_frequency(peak, "Peak")
show_spatial_and_frequency(decay, "Exponential Decay")

""" 3D نمایش    """

from mpl_toolkits.mplot3d import Axes3D

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

ax.plot_surface(X, Y, rect, cmap='viridis')
ax.set_title("Rectangle 3D")
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from scipy.fft import fft2, fftshift

# =========================================================
# 1) ساخت grid
# =========================================================
N = 256
L = 10

x = np.linspace(-L, L, N)
y = np.linspace(-L, L, N)
X, Y = np.meshgrid(x, y)

dx = x[1] - x[0]

# =========================================================
# 2) تعریف توابع
# =========================================================

def rectangle(X, Y, a=2, b=1.5):
    return ((np.abs(X) <= a) & (np.abs(Y) <= b)).astype(float)

def pyramid(X, Y, a=3, b=3):
    return np.maximum(1 - np.abs(X)/a, 0) * np.maximum(1 - np.abs(Y)/b, 0)

def gaussian(X, Y, sigma=1.2):
    return np.exp(-(X**2 + Y**2)/(2*sigma**2))

def peak(X, Y):
    r = np.sqrt(X**2 + Y**2) + 1e-3
    return 1 / r

def exponential_decay(X, Y, a=1.2):
    r = np.sqrt(X**2 + Y**2)
    return np.exp(-a * r)

# =========================================================
# 3) FFT
# =========================================================
def get_fft(f):
    F = fftshift(fft2(f)) * dx * dx
    return np.log1p(np.abs(F))   # برای دید بهتر

# =========================================================
# 4) رسم 3D
# =========================================================
def plot_3d(X, Y, Z, title):
    fig = plt.figure(figsize=(7,5))
    ax = fig.add_subplot(111, projection='3d')

    ax.plot_surface(X, Y, Z, cmap='viridis')
    ax.set_title(title)
    ax.set_xlabel("X")
    ax.set_ylabel("Y")
    ax.set_zlabel("Amplitude")

    ax.view_init(30, -120)
    plt.show()

# =========================================================
# 5) اجرای همه توابع
# =========================================================

# Rectangle
rect = rectangle(X, Y)
plot_3d(X, Y, rect, "Rectangle - Spatial")
plot_3d(X, Y, get_fft(rect), "Rectangle - Frequency")

# Pyramid
pyr = pyramid(X, Y)
plot_3d(X, Y, pyr, "Pyramid - Spatial")
plot_3d(X, Y, get_fft(pyr), "Pyramid - Frequency")

# Gaussian
gauss = gaussian(X, Y)
plot_3d(X, Y, gauss, "Gaussian - Spatial")
plot_3d(X, Y, get_fft(gauss), "Gaussian - Frequency")

# Peak
pk = peak(X, Y)
plot_3d(X, Y, pk, "Peak - Spatial")
plot_3d(X, Y, get_fft(pk), "Peak - Frequency")

# Exponential Decay
decay = exponential_decay(X, Y)
plot_3d(X, Y, decay, "Exponential Decay - Spatial")
plot_3d(X, Y, get_fft(decay), "Exponential Decay - Frequency")

import numpy as np
import matplotlib.pyplot as plt
from scipy.fft import fft2, fftshift, fftfreq
from mpl_toolkits.mplot3d import Axes3D

# =========================================================
# 1) تنظیمات اصلی برای نمایش بهتر
# =========================================================
N = 256           # تعداد نمونه در هر بعد
L = 10.0          # دامنه مکانی: از -L تا +L

x = np.linspace(-L, L, N, endpoint=False)
y = np.linspace(-L, L, N, endpoint=False)
X, Y = np.meshgrid(x, y)

dx = x[1] - x[0]
dy = y[1] - y[0]

# محور فرکانس
u = fftshift(fftfreq(N, d=dx))
v = fftshift(fftfreq(N, d=dy))
U, V = np.meshgrid(u, v)

# =========================================================
# 2) توابع دوبعدی
# =========================================================
def rectangle_2d(X, Y, a=2.0, b=1.5):
    """
    Rectangle with width 2a and height 2b
    """
    return ((np.abs(X) <= a) & (np.abs(Y) <= b)).astype(float)

def pyramid_2d(X, Y, a=3.0, b=3.0):
    """
    2D pyramid = product of two 1D triangular functions
    """
    tx = np.maximum(1.0 - np.abs(X) / a, 0.0)
    ty = np.maximum(1.0 - np.abs(Y) / b, 0.0)
    return tx * ty

def gaussian_2d(X, Y, sigma=1.2):
    """
    Normalized 2D Gaussian
    """
    return (1.0 / (2.0 * np.pi * sigma**2)) * np.exp(-(X**2 + Y**2) / (2.0 * sigma**2))

def peak_2d(X, Y, eps=1e-3):
    """
    Peak function: 1/r, regularized at origin
    """
    R = np.sqrt(X**2 + Y**2)
    return 1.0 / np.maximum(R, eps)

def exponential_decay_2d(X, Y, a=1.2):
    """
    Radial exponential decay: exp(-a r)
    """
    R = np.sqrt(X**2 + Y**2)
    return np.exp(-a * R)

# =========================================================
# 3) FFT دوبعدی
# =========================================================
def compute_fft2(signal):
    """
    Approximation of continuous FT:
    FFT * dx * dy
    """
    return fftshift(fft2(signal)) * dx * dy

# =========================================================
# 4) ابزار نرمال‌سازی برای نمایش سه‌بعدی
# =========================================================
def normalize_for_plot(z):
    z = np.asarray(z, dtype=float)
    zmin = np.min(z)
    zmax = np.max(z)
    if np.isclose(zmax - zmin, 0):
        return np.zeros_like(z)
    return (z - zmin) / (zmax - zmin)

# =========================================================
# 5) رسم سطح سه‌بعدی
# =========================================================
def plot_3d_surface(ax, Xg, Yg, Z, title, xlabel, ylabel, zlabel, cmap="viridis"):
    surf = ax.plot_surface(
        Xg, Yg, Z,
        cmap=cmap,
        linewidth=0,
        antialiased=True,
        rstride=2,
        cstride=2
    )
    ax.set_title(title, fontsize=11)
    ax.set_xlabel(xlabel)
    ax.set_ylabel(ylabel)
    ax.set_zlabel(zlabel)
    ax.view_init(elev=35, azim=-135)
    return surf

# =========================================================
# 6) تولید سیگنال‌ها
# =========================================================
rect = rectangle_2d(X, Y, a=2.0, b=1.5)
pyr = pyramid_2d(X, Y, a=3.0, b=3.0)
gauss = gaussian_2d(X, Y, sigma=1.2)
peak = peak_2d(X, Y, eps=1e-3)
decay = exponential_decay_2d(X, Y, a=1.2)

signals = [
    ("Rectangle", rect),
    ("Pyramid", pyr),
    ("Gaussian", gauss),
    ("Peak", peak),
    ("Exponential Decay", decay),
]

# =========================================================
# 7) محاسبه و رسم 3D برای Spatial و Frequency
# =========================================================
fig = plt.figure(figsize=(18, 30))
fig.suptitle("2D Signals and Their Fourier Transforms - 3D Visualization", fontsize=18, y=0.995)

for i, (name, sig) in enumerate(signals, start=1):
    F = compute_fft2(sig)

    # برای نمایش بهتر:
    # - سیگنال مکانی را به [0,1] نرمال می‌کنیم
    # - طیف فرکانسی را log1p(abs(F)) می‌گیریم و سپس نرمال می‌کنیم
    sig_vis = normalize_for_plot(sig)
    F_vis = normalize_for_plot(np.log1p(np.abs(F)))

    ax1 = fig.add_subplot(5, 2, 2*i - 1, projection='3d')
    ax2 = fig.add_subplot(5, 2, 2*i, projection='3d')

    plot_3d_surface(
        ax1,
        X, Y, sig_vis,
        f"{name} - Spatial Domain (3D)",
        "x", "y", "normalized amplitude",
        cmap="viridis"
    )

    plot_3d_surface(
        ax2,
        U, V, F_vis,
        f"{name} - Frequency Domain (3D, log magnitude)",
        "u", "v", "normalized log |F(u,v)|",
        cmap="magma"
    )

plt.tight_layout(rect=[0, 0, 1, 0.99])
plt.show()

# =========================================================
# 8) نمایش مجدد هر تابع با دامنه‌های بهینه‌تر برای دیدن بهتر جزئیات
#    (اختیاری ولی مفید برای گزارش و درک مفاهیم)
# =========================================================
def plot_single_pair(name, sig):
    F = compute_fft2(sig)
    sig_vis = normalize_for_plot(sig)
    F_vis = normalize_for_plot(np.log1p(np.abs(F)))

    fig = plt.figure(figsize=(15, 6))

    ax1 = fig.add_subplot(1, 2, 1, projection='3d')
    ax2 = fig.add_subplot(1, 2, 2, projection='3d')

    plot_3d_surface(
        ax1, X, Y, sig_vis,
        f"{name} - Spatial Domain",
        "x", "y", "normalized amplitude",
        cmap="viridis"
    )

    plot_3d_surface(
        ax2, U, V, F_vis,
        f"{name} - Frequency Domain",
        "u", "v", "normalized log |F(u,v)|",
        cmap="magma"
    )

    plt.tight_layout()
    plt.show()

plot_single_pair("Rectangle", rect)
plot_single_pair("Pyramid", pyr)
plot_single_pair("Gaussian", gauss)
plot_single_pair("Peak", peak)
plot_single_pair("Exponential Decay", decay)

"""مقایسه تحلیلی با واقعی"""

def sinc(x):
    return np.sinc(x)

F_analytic = (2*2)*sinc(2*2*U) * (2*1.5)*sinc(2*1.5*V)

plt.imshow(np.log(np.abs(F_analytic)+1))
plt.title("Analytical FT")
plt.colorbar()
plt.show()

"""تغییر پارامتر دلخواه

مستطیل بزرگ‌تر → فرکانس فشرده‌تر
"""

for a in [1,2,4]:
    show_spatial_and_frequency(rectangle_2d(X,Y,a,1.5), f"a={a}")

"""موقت"""

!pip -q install numpy scipy matplotlib

import numpy as np
import matplotlib.pyplot as plt

try:
    from scipy.fft import fft2, fftshift
except Exception:
    from numpy.fft import fft2, fftshift


def make_grid(n=512, extent=8.0):
    x = np.linspace(-extent, extent, n, endpoint=False)
    y = np.linspace(-extent, extent, n, endpoint=False)
    X, Y = np.meshgrid(x, y)
    dx = x[1] - x[0]
    dy = y[1] - y[0]
    return X, Y, dx, dy, x, y


def rect2d(X, Y, a=1.5, b=1.0):
    return ((np.abs(X) <= a) & (np.abs(Y) <= b)).astype(float)


def pyramid2d(X, Y, a=2.5, b=2.5):
    Tx = np.maximum(1.0 - np.abs(X) / a, 0.0)
    Ty = np.maximum(1.0 - np.abs(Y) / b, 0.0)
    return Tx * Ty


def gaussian2d(X, Y, sigma=1.0):
    return (1.0 / (2.0 * np.pi * sigma**2)) * np.exp(-(X**2 + Y**2) / (2.0 * sigma**2))


def peak2d(X, Y, eps=1e-3):
    r = np.sqrt(X**2 + Y**2)
    return 1.0 / np.maximum(r, eps)


def exp_decay2d(X, Y, alpha=1.2):
    r = np.sqrt(X**2 + Y**2)
    return np.exp(-alpha * r)


def fft2_continuous_approx(f, dx, dy):
    return fftshift(fft2(np.asarray(f))) * dx * dy


def freq_axes(n, dx, dy):
    fx = np.fft.fftshift(np.fft.fftfreq(n, d=dx))
    fy = np.fft.fftshift(np.fft.fftfreq(n, d=dy))
    return fx, fy


def analytic_rectangle_ft(U, V, a=1.5, b=1.0):
    return (2 * a) * np.sinc(2 * a * U) * (2 * b) * np.sinc(2 * b * V)


def analytic_gaussian_ft(U, V, sigma=1.0):
    return np.exp(-2.0 * (np.pi**2) * (sigma**2) * (U**2 + V**2))


def analytic_peak_ft(U, V, eps=1e-12):
    Rf = np.sqrt(U**2 + V**2)
    return 1.0 / np.maximum(Rf, eps)


def analytic_exp_decay_ft(U, V, alpha=1.2):
    return (2.0 * np.pi * alpha) / np.power(U**2 + V**2 + alpha**2, 1.5)


def plot_pair(ax1, ax2, spatial, spectrum, x, y, fx, fy, title1, title2, cmap="viridis"):
    extent_xy = [x.min(), x.max(), y.min(), y.max()]
    extent_f = [fx.min(), fx.max(), fy.min(), fy.max()]

    im1 = ax1.imshow(spatial, extent=extent_xy, origin="lower", cmap=cmap, aspect="auto")
    ax1.set_title(title1)
    ax1.set_xlabel("x")
    ax1.set_ylabel("y")
    plt.colorbar(im1, ax=ax1, fraction=0.046, pad=0.04)

    im2 = ax2.imshow(np.abs(spectrum), extent=extent_f, origin="lower", cmap=cmap, aspect="auto")
    ax2.set_title(title2)
    ax2.set_xlabel("u")
    ax2.set_ylabel("v")
    plt.colorbar(im2, ax=ax2, fraction=0.046, pad=0.04)


def main():
    n = 512
    extent = 8.0
    X, Y, dx, dy, x, y = make_grid(n=n, extent=extent)
    U, V = np.meshgrid(*freq_axes(n, dx, dy))

    a, b = 1.5, 1.0
    sigma = 1.0
    alpha = 1.2
    eps = 1e-3

    rect = rect2d(X, Y, a=a, b=b)
    pyr = pyramid2d(X, Y, a=2.5, b=2.5)
    gauss = gaussian2d(X, Y, sigma=sigma)
    peak = peak2d(X, Y, eps=eps)
    decay = exp_decay2d(X, Y, alpha=alpha)

    F_rect = fft2_continuous_approx(rect, dx, dy)
    F_pyr = fft2_continuous_approx(pyr, dx, dy)
    F_gauss = fft2_continuous_approx(gauss, dx, dy)
    F_peak = fft2_continuous_approx(peak, dx, dy)
    F_decay = fft2_continuous_approx(decay, dx, dy)

    A_rect = analytic_rectangle_ft(U, V, a=a, b=b)
    A_gauss = analytic_gaussian_ft(U, V, sigma=sigma)
    A_peak = analytic_peak_ft(U, V, eps=1e-12)
    A_decay = analytic_exp_decay_ft(U, V, alpha=alpha)

    spectra = [
        (F_rect, "Rectangle"),
        (F_pyr, "Pyramid"),
        (F_gauss, "Gaussian"),
        (F_peak, "Peak"),
        (F_decay, "Exponential Decay"),
    ]

    spatial_list = [rect, pyr, gauss, peak, decay]
    titles_spatial = [
        f"Spatial domain: Rectangle (a={a}, b={b})",
        "Spatial domain: Pyramid",
        f"Spatial domain: Gaussian (sigma={sigma})",
        f"Spatial domain: Peak (1/r, regularized)",
        f"Spatial domain: Exponential Decay (alpha={alpha})",
    ]
    titles_freq = [
        "Fourier magnitude: Rectangle",
        "Fourier magnitude: Pyramid",
        "Fourier magnitude: Gaussian",
        "Fourier magnitude: Peak",
        "Fourier magnitude: Exponential Decay",
    ]

    fig, axes = plt.subplots(5, 2, figsize=(14, 28))
    fig.suptitle("2D Signals and Their Fourier Transforms", fontsize=18, y=0.995)

    for i, (sig, (Fnum, _name)) in enumerate(zip(spatial_list, spectra)):
        plot_pair(
            axes[i, 0],
            axes[i, 1],
            sig,
            Fnum,
            x,
            y,
            U[0, :],
            V[:, 0],
            titles_spatial[i],
            titles_freq[i],
        )

    plt.tight_layout()
    plt.show()

    fig2, axes2 = plt.subplots(2, 2, figsize=(12, 10))
    fig2.suptitle("Selected Analytic Frequency Responses", fontsize=16)

    comps = [
        ("Rectangle: analytic FT", A_rect, axes2[0, 0]),
        ("Gaussian: analytic FT", A_gauss, axes2[0, 1]),
        ("Peak: reference 1/f", A_peak, axes2[1, 0]),
        ("Exponential Decay: analytic FT", A_decay, axes2[1, 1]),
    ]

    for title, arr, ax in comps:
        im = ax.imshow(np.abs(arr), extent=[U.min(), U.max(), V.min(), V.max()], origin="lower", aspect="auto")
        ax.set_title(title)
        ax.set_xlabel("u")
        ax.set_ylabel("v")
        plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04)

    plt.tight_layout()
    plt.show()


main()